apiVersion: apps/v1
kind: Deployment
metadata:
  name: $DEPLOYMENT_NAME
  labels:
    app: $APP_NAME
spec:
  replicas: $NUMBER_REPLICAS
  selector:
    matchLabels:
      app: $APP_NAME
  template:
    metadata:
      labels:
        app: $APP_NAME
    spec:
      containers:
      - name: $CONTAINER_NAME
        image: $IMAGE_NAME:$IMAGE_TAG
        ports:
        - containerPort: $PORT
