/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.7).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.InlineResponse200;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2019-07-31T01:28:01.736Z")

@Api(value = "health", description = "the health API")
public interface HealthApi {

    @ApiOperation(value = "simple healthcheck", nickname = "simpleHealthCheck", notes = "a simple health check endpoint to ensure the API is running  ", response = InlineResponse200.class, tags={ "devops", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "API running", response = InlineResponse200.class),
        @ApiResponse(code = 500, message = "API Not running") })
    @RequestMapping(value = "/health",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<InlineResponse200> simpleHealthCheck();

}
