/*
 * Vaults Manager API
 *
 * Vaults Manager
 *
 * OpenAPI spec version: 1.0.0
 * Contact: aawadall@ualberta.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using IO.Swagger.Attributes;
using IO.Swagger.Security;
using Microsoft.AspNetCore.Authorization;
using IO.Swagger.Models;

namespace IO.Swagger.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class DevopsApiController : ControllerBase
    { 
        /// <summary>
        /// simple healthcheck
        /// </summary>
        /// <remarks>a simple health check endpoint to ensure the API is running  </remarks>
        /// <response code="200">API running</response>
        /// <response code="500">API Not running</response>
        [HttpGet]
        [Route("/awadallah/VaultsManager/1.0.0/health")]
        [ValidateModelState]
        [SwaggerOperation("SimpleHealthCheck")]
        [SwaggerResponse(statusCode: 200, type: typeof(InlineResponse200), description: "API running")]
        public virtual IActionResult SimpleHealthCheck()
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(InlineResponse200));

            //TODO: Uncomment the next line to return response 500 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(500);

            string exampleJson = null;
            exampleJson = "{\n  \"status\" : \"status\"\n}";
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<InlineResponse200>(exampleJson)
            : default(InlineResponse200);
            //TODO: Change the data returned
            return new ObjectResult(example);
        }
    }
}
